In [2]:
import numpy as np

In [13]:
arg0 = np.linspace(0, 4, 5)
arg1 = np.linspace(0, 4, 5)
arg2 = np.linspace(0, 4, 5)

In [14]:
def func1(arg0, arg1, arg2):
    return arg0*1E0 + arg1*1E1 + arg2*1E2
    

In [15]:
vfunc1 = np.vectorize(func1)

In [20]:
ANS = vfunc1(arg1, arg2, arg3)

In [21]:
ANS

array([  0., 111., 222., 333., 444.])

In [22]:
arg0

array([0., 1., 2., 3., 4.])

In [5]:
z = np.random.randint(5, size = (4,4))

In [6]:
z

array([[4, 3, 3, 1],
       [3, 1, 2, 4],
       [4, 4, 0, 2],
       [1, 3, 1, 0]])

In [8]:
index = [2,3]

In [10]:
z[index[0],index[1]]

2

In [11]:
x = 3

In [12]:
y = x

In [13]:
print(y)

3


In [14]:
x = 2

In [15]:
print(y)

3
